# Generated by Django 3.1.7 on 2021-04-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='imageApp',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
